services:
  - type: web
    name: barbearia-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JWT_SECRET
        value: minha-chave-secreta
      - key: MONGO_URI
        value: mongodb+srv://barbeariaUser:SenhaSegura123!@cluster0.mongodb.net/barbearia?retryWrites=true&w=majority
      - key: ADMIN_PHONE
        value: +5582993230395@c.us
      - key: PORT
        value: 3000